-- GlobalDoc Connect: admin + auth verification SQL
-- Run in Supabase Dashboard > SQL Editor.
-- This project currently authenticates the platform admin through the app backend
-- using ADMIN_EMAIL and ADMIN_PASSWORD. The public.admins row below is kept for
-- database role lookup and future Supabase-backed admin checks.

begin;

create table if not exists public.admins (
  id integer generated by default as identity primary key,
  email text not null unique
);

insert into public.admins (id, email)
values (2, 'shafiuabdullahi.sa3@gmail.com')
on conflict (email) do update
set email = excluded.email;

-- Confirm the admin row exists.
select id, email
from public.admins
where email = 'shafiuabdullahi.sa3@gmail.com';

-- Confirm whether this email also exists in Supabase Auth.
-- If this returns no rows, create the user from Authentication > Users,
-- then set/reset the password there. Do not store passwords in public.admins.
select id, email, email_confirmed_at, created_at
from auth.users
where lower(email) = lower('shafiuabdullahi.sa3@gmail.com');

commit;

-- Required Supabase Auth URL settings:
-- Site URL:
--   https://globaldoctorplatform.vercel.app
--
-- Redirect URLs:
--   https://globaldoctorplatform.vercel.app/auth/callback
--   http://localhost:5173/auth/callback
--
-- Google Cloud OAuth Authorized JavaScript origins:
--   https://globaldoctorplatform.vercel.app
--   http://localhost:5173
--
-- Google Cloud OAuth Authorized redirect URI:
--   https://YOUR_SUPABASE_PROJECT_REF.supabase.co/auth/v1/callback
