-- GlobalDoc Connect: admin + auth verification SQL
-- Run in Supabase Dashboard > SQL Editor.
-- This project currently authenticates the platform admin through the app backend
-- using ADMIN_EMAIL and ADMIN_PASSWORD. Your Supabase public.admins table also
-- has a NOT NULL password column, so the seed below fills it to satisfy the
-- existing schema. For full production security, use Supabase Auth password
-- reset/update flows instead of relying on a public password column.

begin;

create table if not exists public.admins (
  id integer generated by default as identity primary key,
  email text not null unique,
  password text not null,
  name text,
  created_at timestamptz not null default now()
);

alter table public.admins
  alter column password set not null;

insert into public.admins (id, email, password, name)
values (2, 'shafiuabdullahi.sa3@gmail.com', '014/Pt/014', 'System Admin')
on conflict (email) do update
set password = excluded.password,
    name = excluded.name;

-- Confirm the admin row exists.
select id, email, name, created_at
from public.admins
where email = 'shafiuabdullahi.sa3@gmail.com';

-- Confirm whether this email also exists in Supabase Auth.
-- If this returns no rows, create the user from Authentication > Users,
-- then set/reset the password there. Do not store passwords in public.admins.
select id, email, email_confirmed_at, created_at
from auth.users
where lower(email) = lower('shafiuabdullahi.sa3@gmail.com');

commit;

-- Required Supabase Auth URL settings:
-- Site URL:
--   https://globaldoctorplatform.vercel.app
--
-- Redirect URLs:
--   https://globaldoctorplatform.vercel.app/auth/callback
--   http://localhost:5173/auth/callback
--
-- Google Cloud OAuth Authorized JavaScript origins:
--   https://globaldoctorplatform.vercel.app
--   http://localhost:5173
--
-- Google Cloud OAuth Authorized redirect URI:
--   https://YOUR_SUPABASE_PROJECT_REF.supabase.co/auth/v1/callback
