import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { getFairConsultationTokens } from '../src/lib/consultationPricing.js'

const server = readFileSync(new URL('../server/index.js', import.meta.url), 'utf8')
const schema = readFileSync(new URL('../SUPABASE_FULL_REPAIR_SCHEMA.sql', import.meta.url), 'utf8')
const calendar = readFileSync(new URL('../src/components/CalendarScheduler.jsx', import.meta.url), 'utf8')
const adminDashboard = readFileSync(new URL('../src/pages/AdminDashboard.jsx', import.meta.url), 'utf8')
const platformAdminDashboard = readFileSync(new URL('../src/pages/PlatformAdminDashboard.jsx', import.meta.url), 'utf8')
const doctorAvailabilityManager = readFileSync(new URL('../src/components/DoctorAvailabilityManager.jsx', import.meta.url), 'utf8')
const fileManager = readFileSync(new URL('../src/components/FileManager.jsx', import.meta.url), 'utf8')
const doctorDashboard = readFileSync(new URL('../src/pages/AdminDashboard.jsx', import.meta.url), 'utf8')
const chatPanel = readFileSync(new URL('../src/components/ChatPanel.jsx', import.meta.url), 'utf8')
const communityChat = readFileSync(new URL('../src/components/DoctorCommunityChat.jsx', import.meta.url), 'utf8')
const patientDashboard = readFileSync(new URL('../src/pages/PatientDashboard.jsx', import.meta.url), 'utf8')
const doctorSelection = readFileSync(new URL('../src/components/DoctorSelection.jsx', import.meta.url), 'utf8')
const patientAuth = readFileSync(new URL('../src/components/PatientAuth.jsx', import.meta.url), 'utf8')
const appointmentScheduler = readFileSync(new URL('../src/components/AppointmentScheduler.jsx', import.meta.url), 'utf8')
const vercel = readFileSync(new URL('../vercel.json', import.meta.url), 'utf8')
const apiFetchClient = readFileSync(new URL('../src/lib/apiFetch.js', import.meta.url), 'utf8')
const forgotPassword = readFileSync(new URL('../src/pages/ForgotPassword.jsx', import.meta.url), 'utf8')
const consultationPricing = readFileSync(new URL('../src/lib/consultationPricing.js', import.meta.url), 'utf8')
const consultationRatingPrompt = readFileSync(new URL('../src/components/ConsultationRatingPrompt.jsx', import.meta.url), 'utf8')
const videoChatPanel = readFileSync(new URL('../src/components/VideoChatPanel.jsx', import.meta.url), 'utf8')
const landingPage = readFileSync(new URL('../src/pages/LandingPage.jsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')

test('doctor availability is deterministic and database-backed', () => {
  assert.match(server, /doctor_availability_slots/)
  assert.match(server, /getDoctorAvailabilityForDate/)
  assert.match(adminDashboard, /DoctorAvailabilityManager/)
  assert.match(doctorAvailabilityManager, /PATCH/)
  assert.doesNotMatch(server, /DOCTOR AVAILABILITY \(mock\)/)
  assert.doesNotMatch(calendar, /generateMockSlots/)
  assert.doesNotMatch(calendar, /Math\.random/)
  assert.match(calendar, /Submit appointment/)
  assert.match(calendar, /disabled=\{!selectedDate \|\| !selectedTime \|\| scheduling\}/)
  assert.match(calendar, /This doctor has no available time on this date/)
})

test('admin files are persisted instead of mocked', () => {
  assert.match(schema, /CREATE TABLE IF NOT EXISTS public\.admin_files/)
  assert.match(server, /from\('admin_files'\)/)
  assert.match(platformAdminDashboard, /FileManager/)
  assert.match(fileManager, /headers/)
  assert.doesNotMatch(server, /mockFiles/)
  assert.doesNotMatch(server, /Sample Document\.pdf/)
})

test('video signaling requires Supabase persistence', () => {
  assert.match(server, /video_signals/)
  assert.match(server, /rememberFallbackVideoSignal/)
  assert.match(server, /readFallbackVideoSignals/)
  assert.doesNotMatch(server, /stored in memory only/)
  assert.doesNotMatch(server, /videoSignalRooms/)
})

test('Kora payment initialization does not return fake checkout success without configuration', () => {
  assert.match(server, /Kora payment is not configured/)
  assert.match(server, /Kora subscription payment is not configured/)
  assert.doesNotMatch(server, /Payment initialized \(mock - no KORA key\)/)
  assert.doesNotMatch(server, /Subscription payment initialized \(mock - no KORA key\)/)
  assert.doesNotMatch(server, /Payment request queued\. Add KORA_SECRET_KEY/)
})

test('patient token wallet writes tolerate older schema cache', () => {
  assert.match(server, /async function upsertPatientTokenBalance/)
  assert.match(server, /getMissingColumnName\(result\.error\) === 'updated_at'/)
  assert.match(server, /mode: 'without_updated_at'/)
  assert.match(server, /isMissingConflictConstraintError\(result\.error\)/)
  assert.match(server, /mode: 'update_without_constraint'/)
  assert.match(server, /const \[walletUpdate, patientUpdate\] = await Promise\.all\(\[/)
  assert.match(schema, /ADD CONSTRAINT patient_tokens_patient_id_key UNIQUE \(patient_id\)/)
})

test('Kora verification records actual payment method details', () => {
  assert.match(server, /function extractKoraPaymentMethod/)
  assert.match(server, /paymentMethod/)
  assert.match(server, /bank_transfer/)
  assert.match(server, /bank_deposit/)
  assert.match(server, /async function annotatePaymentFromKora/)
  assert.match(server, /koraPaymentMethod/)
  assert.match(server, /payment_method: method\.paymentMethod/)
})

test('doctor withdrawal sends current payout form details', () => {
  assert.match(adminDashboard, /JSON\.stringify\(\{ tokens, payoutDetails \}\)/)
  assert.match(server, /normalizePayoutDetailsFromBody/)
  assert.match(server, /req\.body\?\.payoutDetails/)
})

test('schema includes recent repair columns and indexes', () => {
  assert.match(schema, /last_seen_at timestamptz/)
  assert.match(schema, /ALTER TABLE public\.patient_tokens ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now\(\)/)
  assert.match(schema, /reference text/)
  assert.match(schema, /metadata jsonb/)
  assert.match(schema, /idx_doctor_availability_slots_doctor_date/)
  assert.match(schema, /doctor_availability_slots_doctor_date_time_key/)
  assert.match(schema, /idx_token_transactions_patient_reference/)
  assert.match(server, /async function upsertByConflictAdaptive/)
  assert.match(server, /upsertByConflictAdaptive\('platform_balances'/)
  assert.match(server, /upsertByConflictAdaptive\('server_settings'/)
})

test('appointment scheduling avoids repeated slow work and redundant Supabase auth failure', () => {
  assert.match(server, /const \[slotResult, appointmentResult\] = await Promise\.all\(\[slotPromise, appointmentPromise\]\)/)
  assert.match(server, /deductPatientTokens\(patientId, requiredTokens, '', \{ currentBalance: balance \}\)/)
  assert.match(server, /Appointment was already scheduled/)
  assert.match(server, /req\.body\.slotDate/)
  assert.match(calendar, /slotDate,\s*slotTime: selectedTime/)
  assert.match(calendar, /date\.getFullYear\(\)/)
  assert.match(appointmentScheduler, /slotDate: scheduledDate\.slice\(0, 10\)/)
  assert.match(server, /function getAppointmentLocalSlotTime/)
  assert.match(server, /isMissingConflictConstraintError\(error\)[\s\S]*insertAdaptive\('doctor_availability_slots', rows\)/)
  assert.doesNotMatch(patientAuth, /onAuth\(\{ type: 'login', patient: result\.patient \}\)[\s\S]{0,120}signInWithPassword/)
})

test('production API avoids cold-start diagnostics and allows enough time for database recovery', () => {
  assert.match(server, /process\.env\.NODE_ENV !== 'production' \|\| process\.env\.RUN_STARTUP_DIAGNOSTICS === 'true'/)
  assert.equal(JSON.parse(vercel).functions['api/index.js'].maxDuration, 30)
})

test('active UI workflows tolerate non-JSON gateway errors', () => {
  assert.match(apiFetchClient, /export async function readApiJson/)
  assert.match(apiFetchClient, /const copy = response\.clone\(\)/)
  assert.match(patientDashboard, /readApiJson\(response\)/)
  assert.match(doctorDashboard, /readApiJson\(response\)/)
  assert.match(chatPanel, /readApiJson\(response\)/)
})

test('Gmail SMTP selects and normalizes a valid app-password candidate safely', () => {
  assert.match(server, /function normalizeEnvSecret/)
  assert.match(server, /GMAIL_APP_PASSWORD/)
  assert.match(server, /passwordCandidates\.find\(\(candidate\) => \/\^\[a-z0-9\]\{16\}\$\/i\.test\(candidate\.pass\)\)/)
  assert.match(server, /gmailAppPasswordFormat/)
  assert.match(server, /Google OAuth client IDs and normal Gmail passwords do not work for SMTP/)
  assert.match(server, /Gmail SMTP requires a separate 16-character App Password/)
  assert.match(server, /GMAIL_REFRESH_TOKEN/)
  assert.match(server, /type: 'OAuth2'/)
})

test('password reset and clinical notification emails confirm real SMTP delivery', () => {
  assert.match(server, /recordEmailDelivery/)
  assert.match(server, /sendUserNotificationEmail/)
  assert.match(server, /purpose: 'password_reset'/)
  assert.match(server, /Password reset token storage failed/)
  assert.match(server, /return res\.status\(503\)\.json\(\{ error: emailResult\.reason/)
  assert.match(server, /processDueAppointmentEmailReminders/)
  assert.match(server, /purpose: 'prescription'/)
  assert.match(server, /purpose: 'lab_order'/)
  assert.match(server, /purpose: 'token_purchase_receipt'/)
  assert.match(schema, /CREATE TABLE IF NOT EXISTS public\.email_delivery_logs/)
  assert.match(forgotPassword, /if \(!response\.ok\) throw new Error\(data\.error/)
})

test('doctor online status requires a recent heartbeat', () => {
  assert.match(server, /doctor\.last_seen_at \|\| nested\.last_seen_at/)
  assert.match(server, /if \(!rawSeenAt\) return false/)
  assert.doesNotMatch(server, /doctor\.last_seen_at \|\| doctor\.updated_at \|\| nested\.last_seen_at \|\| nested\.updated_at/)
  assert.match(server, /is_online: true, verified: true, license_verified: true, last_seen_at: onlineAt/)
  assert.match(server, /A valid doctor session is required to update online status/)
  assert.match(server, /A valid patient session is required to update online status/)
  assert.match(app, /'x-session-proof': authDoctor\.session_proof/)
  assert.match(app, /const nextDoctor = \{ \.\.\.current, \.\.\.data\.doctor \}/)
  assert.match(patientDashboard, /'x-session-proof': patient\.session_proof/)
})

test('PHC facility consultations use facility wallet funding instead of patient tokens', () => {
  assert.match(server, /channel === 'facility_phc'/)
  assert.match(server, /facility_topup_ngn: total/)
  assert.match(server, /doctor_ngn: total/)
  assert.match(server, /chargePatient: false/)
  assert.match(server, /debitFacilityTopup: channel === 'facility_phc'/)
})

test('specialty referral creation uses bounded snapshot and non-blocking notifications', () => {
  assert.match(server, /snapshot query timeout/)
  assert.match(server, /Referral doctor notifications skipped/)
  assert.match(server, /buildQuery\(false\)/)
})

test('specialty referral acceptance is idempotent and opens room without charging patient again', () => {
  assert.match(server, /Existing consultation room reopened/)
  assert.match(server, /source: 'specialty_referral',[\s\S]*chargePatient: false/)
  assert.match(server, /Referral accepted and consultation room opened/)
  assert.match(server, /if \(referral\.target_doctor_id\) return String\(referral\.target_doctor_id\) === targetDoctorId/)
  assert.match(server, /if \(status === 'accepted'\) return String\(referral\.accepted_by_doctor_id/)
})

test('patient token balance reconciles wallet and patient mirrors', () => {
  assert.match(server, /const ledgerAvailable = !ledgerResult\.error && ledgerRows\.length > 0/)
  assert.match(server, /const reconciledBalance = ledgerAvailable/)
  assert.match(server, /token_transactions'\)\.select\('amount'\)/)
  assert.match(server, /ledgerRows\.reduce/)
  assert.match(server, /Patient token mirror repair skipped/)
  assert.match(server, /async function ensurePatientTokenLedgerBaseline/)
  assert.match(server, /opening-balance-\$\{patientId\}/)
  assert.match(schema, /Legacy wallet opening balance/)
})

test('consultation start creates the room quickly and alerts the doctor waiting room', () => {
  assert.match(server, /Promise\.all\(\[\s*findPatientByIdentifier\(patientId\),\s*getDoctorProfile\(doctorId\)/)
  assert.match(server, /Consultation room creation timed out/)
  assert.match(server, /settlementPending: true/)
  assert.match(server, /type: 'join_request',[\s\S]*source: 'consultation_start'/)
  assert.match(server, /last_seen_at: now/)
  assert.match(doctorDashboard, /\{selectedConsultationPatient \? 'Change patient' : 'Show patients'\}/)
  assert.match(server, /if \(chargePatient \|\| tokensCharged > 0\) consultationUpdates\.patient_tokens_charged = tokensCharged/)
  assert.match(server, /function calculateDirectConsultationProration/)
  assert.match(server, /transactionType: 'refund'/)
  assert.match(server, /patient_tokens_refunded/)
  assert.match(schema, /patient_tokens_refunded integer DEFAULT 0/)
  assert.match(videoChatPanel, /callStartedAtRef/)
  assert.match(videoChatPanel, /onEndCall\?\.\(\{ elapsedMinutes, elapsedSeconds \}\)/)
  assert.match(doctorDashboard, /durationMin: Number\.isFinite\(elapsedMinutes\) \? elapsedMinutes : selectedConsultation\.duration_min/)
  assert.match(patientDashboard, /durationMin: Number\.isFinite\(elapsedMinutes\) \? elapsedMinutes : activeConsultation\?\.duration_min/)
  assert.match(patientDashboard, /unused token\(s\) were refunded/)
  assert.match(doctorSelection, /startingConsultation/)
  assert.match(doctorSelection, /Opening consultation\.\.\./)
})

test('Kora token purchases are inferred from older payment references', () => {
  assert.match(server, /function getPaymentPurpose\(payment\)/)
  assert.match(server, /reference\.startsWith\('kora-token-'\)/)
  assert.match(server, /getPaymentPurpose\(payment\) === 'token_purchase'/)
  assert.match(server, /getPaymentPurpose\(annotatedPayment\) === 'token_purchase'/)
  assert.match(server, /skipTransaction: true/)
  assert.match(server, /String\(claim\.error\.code \|\| ''\) === '23505'/)
  assert.match(schema, /CREATE UNIQUE INDEX IF NOT EXISTS uq_token_transactions_patient_reference/)
})

test('doctor dashboard uses waiting-room alert without forced tab navigation', () => {
  assert.match(doctorDashboard, /Patient waiting now/)
  assert.match(doctorDashboard, /animate-ping/)
  assert.doesNotMatch(doctorDashboard, /hasAutoOpenedPatients/)
})

test('doctor queue hides offline patients and expires stale waiting signals', () => {
  assert.match(server, /function isPatientRecentlyOnline/)
  assert.match(server, /const videoWaiting = patientOnline && recentJoinRequest/)
  assert.match(server, /rows = rows\.filter\(\(patient\) => patient\.is_online\)/)
  assert.match(server, /Date\.now\(\) - createdAt <= PATIENT_ONLINE_WINDOW_MS/)
  assert.match(patientDashboard, /window\.setInterval\(markOnline, 60 \* 1000\)/)
  assert.match(schema, /ALTER TABLE public\.patients ADD COLUMN IF NOT EXISTS last_seen_at timestamptz/)
})

test('accepted offline referrals do not force an empty doctor video workspace', () => {
  assert.match(doctorDashboard, /The patient is offline, so the consultation room will appear/)
  assert.match(server, /The patient is offline and will be notified to join later/)
  assert.match(server, /room will become available when they come online/)
})

test('chat panels keep typing stable while messages synchronize inside fixed scroll areas', () => {
  assert.match(chatPanel, /requestInFlightRef/)
  assert.match(chatPanel, /stickToBottomRef/)
  assert.match(chatPanel, /messages\.map/)
  assert.match(chatPanel, /h-\[420px\] overflow-y-auto overscroll-contain/)
  assert.doesNotMatch(chatPanel, /setLoading\(true\)/)
  assert.match(communityChat, /requestInFlightRef/)
  assert.match(communityChat, /messages\.map/)
  assert.match(communityChat, /h-\[420px\].*overflow-y-auto overscroll-contain/)
  assert.match(server, /res\.status\(201\)\.json\(\{ communityMessage, message: 'Community message sent' \}\)/)
})

test('consultation pricing caps general practice and protects specialist minimums', () => {
  assert.equal(getFairConsultationTokens({ specialty: '', price: { basic: 50 } }, 'basic'), 20)
  assert.equal(getFairConsultationTokens({ specialty: 'General Practitioner', price: { basic: 12 } }, 'basic'), 12)
  assert.equal(getFairConsultationTokens({ specialty: 'General Practitioner', price: { basic: 50 } }, 'basic'), 20)
  assert.equal(getFairConsultationTokens({ specialty: 'Cardiology', price: { basic: 20 } }, 'basic'), 40)
  assert.equal(getFairConsultationTokens({ specialty: 'Cardiology', price: { premium: 80 } }, 'premium'), 80)
  assert.match(consultationPricing, /GP_MAX_CONSULTATION_TOKENS = 20/)
  assert.match(consultationPricing, /SPECIALIST_MIN_CONSULTATION_TOKENS = 40/)
  assert.match(consultationPricing, /Math\.min\(GP_MAX_CONSULTATION_TOKENS/)
  assert.match(consultationPricing, /Math\.max\(SPECIALIST_MIN_CONSULTATION_TOKENS/)
  assert.match(server, /const requiredTokens = getFairConsultationTokens\(doctor, subscriptionType\)/)
  assert.match(server, /function buildDoctorConsultationPrice/)
  assert.match(server, /price: buildDoctorConsultationPrice\(payload\.specialty, payload\.consultationFee\)/)
  assert.doesNotMatch(server, /Math\.min\(20, getFairConsultationTokens\(doctor, subscriptionType\)\)/)
  assert.match(schema, /LEAST\(GREATEST\(COALESCE\(fee, consultation_fee, 20\), 1\), 20\)/)
  assert.match(landingPage, /consultationTokensToUsd\(getFairConsultationTokens\(doctor, 'basic'\)\)/)
  assert.doesNotMatch(landingPage, /\$\{doctor\.fee\}\/consult/)
})

test('completed consultations require one persistent patient rating', () => {
  assert.match(server, /app\.get\('\/api\/reviews\/pending'/)
  assert.match(server, /consultation_id: consultationId/)
  assert.match(server, /ratingRequired: true/)
  assert.match(server, /Ask your patient for a rating/)
  assert.match(schema, /uq_reviews_consultation_patient/)
  assert.match(schema, /UPDATE public\.reviews older[\s\S]*SET consultation_id = NULL/)
  assert.doesNotMatch(schema, /DELETE FROM public\.reviews older/)
  assert.match(consultationRatingPrompt, /A rating is required after each completed consultation/)
  assert.match(consultationRatingPrompt, /Submit rating and continue/)
  assert.match(patientDashboard, /ConsultationRatingPrompt/)
  assert.match(patientDashboard, /consultationId: activeConsultationId,[\s\S]*patientId: patient\.id,[\s\S]*actionProof: activeConsultation\?\.action_proof/)
  assert.match(doctorDashboard, /onEndCall=\{handleDoctorEndConsultation\}/)
  assert.match(videoChatPanel, /onEndCall\?\.\(\{ elapsedMinutes, elapsedSeconds \}\)/)
  assert.match(server, /Patient, doctor, or facility credentials are required to complete this consultation/)
  assert.match(server, /Consultation was already completed/)
  assert.match(server, /function createConsultationProof/)
  assert.match(server, /function verifyConsultationProof/)
  assert.match(server, /function createActorSessionProof/)
  assert.match(server, /function verifyActorSessionProof/)
  assert.match(server, /timingSafeEqual/)
  assert.match(server, /A valid patient consultation proof is required to submit this rating/)
  assert.match(consultationRatingPrompt, /actionProof: consultation\.action_proof/)
  assert.match(doctorDashboard, /actionProof: selectedConsultation\.action_proof/)
  assert.match(doctorDashboard, /'x-session-proof': doctor\.session_proof/)
  assert.match(patientDashboard, /'x-session-proof': patient\.session_proof/)
  assert.match(consultationRatingPrompt, /'x-session-proof': sessionProof/)
  assert.match(patientDashboard, /parsed\?\.id && parsed\?\.session_proof/)
  assert.match(server, /process\.env\.JWT_SECRET \|\| process\.env\.SUPABASE_SERVICE_ROLE_KEY/)
  assert.doesNotMatch(server, /process\.env\.JWT_SECRET \|\| supabaseServiceKey/)
})
