import { useState } from 'react'
import { Search, Mail, Clock, CheckCircle2, AlertCircle } from 'lucide-react'
import { apiFetch } from '../lib/apiFetch'

function badgeClass(status) {
  const value = String(status || 'new').toLowerCase()
  if (value === 'closed') return 'bg-emerald-50 text-emerald-700 ring-emerald-100'
  if (value === 'open' || value === 'assigned') return 'bg-blue-50 text-blue-700 ring-blue-100'
  return 'bg-amber-50 text-amber-700 ring-amber-100'
}

function RequestTracker() {
  const [requestId, setRequestId] = useState('')
  const [email, setEmail] = useState('')
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')

  const loadItems = async (event) => {
    event?.preventDefault?.()
    setNotice('')
    setItems([])
    const params = new URLSearchParams()
    if (requestId.trim()) params.set('caseId', requestId.trim())
    if (email.trim()) params.set('email', email.trim())
    if (!params.toString()) {
      setNotice('Enter your request ID or email address.')
      return
    }
    setLoading(true)
    try {
      const response = await apiFetch(`/api/support/tickets?${params.toString()}`)
      const payload = await response.json().catch(() => ({}))
      if (!response.ok) throw new Error(payload.error || 'Could not load requests.')
      setItems(payload.tickets || [])
      if ((payload.tickets || []).length === 0) setNotice('No request found for those details.')
    } catch (error) {
      setNotice(error.message || 'Could not load requests.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <main className="mx-auto max-w-6xl px-6 py-10 sm:px-8">
      <section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl shadow-slate-200/70">
        <div className="bg-gradient-to-br from-slate-950 via-brand-800 to-brand-600 px-6 py-8 text-white sm:px-10">
          <p className="inline-flex items-center rounded-full bg-white/15 px-4 py-2 text-xs font-bold uppercase tracking-[0.22em] text-brand-50">Request tracker</p>
          <h1 className="mt-5 text-3xl font-bold sm:text-4xl">Track your GlobalDoc request</h1>
          <p className="mt-3 max-w-2xl text-sm leading-7 text-brand-50/90">Use the ID generated by the assistant or your email address to check the latest status.</p>
        </div>

        <form onSubmit={loadItems} className="grid gap-4 p-6 sm:grid-cols-[1fr_1fr_auto] sm:p-8">
          <label className="space-y-1 text-sm font-semibold text-slate-700">Request ID<input value={requestId} onChange={(event) => setRequestId(event.target.value)} placeholder="GDC-20260602-ABC123" className="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-400" /></label>
          <label className="space-y-1 text-sm font-semibold text-slate-700">Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@email.com" className="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-brand-400" /></label>
          <button type="submit" disabled={loading} className="self-end rounded-2xl bg-brand-700 px-6 py-3 font-bold text-white shadow-lg shadow-brand-700/20 hover:bg-brand-600 disabled:bg-slate-300">{loading ? 'Searching...' : <span className="inline-flex items-center gap-2"><Search className="h-4 w-4" /> Search</span>}</button>
        </form>

        {notice && <div className="mx-6 mb-6 rounded-2xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800 sm:mx-8"><AlertCircle className="mr-2 inline h-4 w-4" />{notice}</div>}

        <div className="space-y-4 px-6 pb-8 sm:px-8">
          {items.map((item) => (
            <article key={item.id} className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-5">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">{item.id}</p><h2 className="mt-2 text-xl font-bold text-slate-900">{item.subject || 'Request'}</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><Mail className="h-4 w-4" /> {item.email}</p></div>
                <span className={`rounded-full px-3 py-1 text-xs font-bold ring-1 ${badgeClass(item.status)}`}>{item.status || 'new'}</span>
              </div>
              <p className="mt-4 whitespace-pre-wrap rounded-2xl bg-white p-4 text-sm leading-7 text-slate-700">{item.complaint}</p>
              <div className="mt-4 grid gap-3 sm:grid-cols-3">
                <div className="rounded-2xl bg-white p-3 text-sm text-slate-600"><Clock className="mr-2 inline h-4 w-4 text-brand-700" /> Created: {item.created_at ? new Date(item.created_at).toLocaleString() : '—'}</div>
                <div className="rounded-2xl bg-white p-3 text-sm text-slate-600"><CheckCircle2 className="mr-2 inline h-4 w-4 text-brand-700" /> Assigned: {item.assigned_to || 'Pending'}</div>
                <div className="rounded-2xl bg-white p-3 text-sm text-slate-600">Files: {(item.support_files || []).length}</div>
              </div>
              {item.notes && <p className="mt-4 rounded-2xl bg-brand-50 p-4 text-sm leading-7 text-brand-900"><strong>Agent notes:</strong> {item.notes}</p>}
            </article>
          ))}
        </div>
      </section>
    </main>
  )
}

export default RequestTracker
